### ISSUE TITLE
Collapsed nodes

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#16]
Nodes that have only one entry are collapsed by default.

It doesn't make much sense, since the text is not very long or tall anyway.

**Comment by hairybreeches** [comment]
Hi Luis, thanks for the tip!

Yes, this is an interesting one! We collapse all nodes that represent < 5% of the total query time, including as you point out, nodes with only one or no children.

It's true that collapsing these nodes doesn't save you much vertical space individually - although the nodes with only one child really add up on some very long plans. However, we ended up going with this since we like the fact that it hides/de-emphasises the nodes & information for single-node subtrees which don't take up very much time. The text is greyed out and is more summary in nature, hopefully distracting you less with information which is not so useful - since these nodes are fast anyway.

What do you think? Would you rather see fast subtrees of only one or two nodes expanded by default?

**Comment by lrweck** [comment]
Fast subtrees of 2+ nodes can be collapsed, since it doesn't add much in terms of what I can do about it to the whole thing. If it only has one node, I think it can be shown to give a better overall visualization of what's going on, but it comes down to personal perference, really.

**Comment by mchristofides** [comment]
Nice suggestion. We considered this initially but thought the focus on performance was worth it.

We're also considering adding more information to (at least some) tree nodes in the future, so their height may increase when not collapsed.  

It feels like there could be a nice middle ground though, perhaps instead of saying 1 node, it could have the operation name, but still de-emphasized. Not a perfect example, but like this:

![collapsed-single-node](https://user-images.githubusercontent.com/10532911/66148846-bbb7f480-e609-11e9-8a50-d89fe988e3d0.png)

**Comment by hairybreeches** [comment]
I'm still not sure on this one. The thing I really like about the current solution is that the +/- buttons behave consistently. In this example, you'd have a + button which, when pressed, wouldn't expand any tree, but only change the colour of the text.

I think we should fold this into a larger rethink of how we show information in the tree. Perhaps a really good solution to this will be more obvious when we solve other, connected issues like:
* How do we combine consecutive collapsed branches to save space
* How do we include top-level information (eg table name on reads) in an easily accessible manner from the tree?

**Comment by hairybreeches** [comment]
Now that we show the table names on the tree, hiding a single node means you are probably hiding a read node with a table name, which means that it's much harder to tell where the data is coming from.

I think this is an obvious win now, so I've pushed a change doing it.

Deployed at 14:44 03/02/2020, change 786b2dd05f7952ad934fca2e83080cd326f6c649
