### ISSUE TITLE
Incorrect number of rows

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#19]
Plans 5d3be0b3-e1ec-42bb-8cdc-0c4068ac3811 and edf4a9cb-9a55-4752-94b0-dabeb0401002 show that "In this case, 0 out of *nnnn* table rows were returned after filtering (0%)."

When in reality, the correct number of rows is shown on the node above (Gather).

**Comment by hairybreeches** [comment]
Hi Luis -

I'm afraid this is an artifact of how postgres records rows - as a per-loop average rounded to the nearest row. Because the operation you're talking about has five loops, which produce two rows in total, it's rounded down to zero rows per loop in the plan. You can read more about how actual values are recorded here: https://www.pgmustard.com/blog/2019/9/17/postgres-execution-plans-field-glossary#actual-values

Did this cause you any problems? What were you hoping to see, or learn, that this mislead you with? Did it slow you down in working out what was wrong?

Thanks

Dave

**Comment by lrweck** [comment]
Looking at the plan it appears as if there were no rows returned.

![image](https://user-images.githubusercontent.com/26086198/68307700-71071d80-008a-11ea-9799-e8f79cae95f5.png)

Maybe it could be shown the sum of the number of rows for all loops?

**Comment by hairybreeches** [comment]
What I'm trying to say is that this is a function of the postgres query plans themselves. The query plan you pasted in didn't say that this operation returns 2 rows, all it said is that it returned 0 rows per loop, and executed 5 loops.

Barring a change in the way postgres writes query plans, I think it will be very hard for us to make sure that the row count is exactly accurate. But I'd really like to understand why this is important to you, so that we can make sure that you can see the information you need to see in order to diagnose the performance of your query. What were you trying to achieve when you were looking at the row counts, and how did it slow you down?

**Comment by hairybreeches** [comment]
I'm going to close this issue, let me know if you've got anything more to say or if there's anything more we can do on it.
