### ISSUE TITLE
Table Bloat

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#20]
Table bloat can also occur in highly updated tables, which is the case for this one.

Maybe suggest the user to check if autovacuum is running sufficiently, or as you already do, ask the user to run it manually. Please add a paragraph  explaining that it takes a lock on the table. Users running vacuum on production environments should do it so very carefully.

![image](https://user-images.githubusercontent.com/26086198/68800801-8acfd400-0639-11ea-923b-7e92e7ec9877.png)

Edit:

Looking at the blogpost referenced, my table doesn't even have that much bloat.

![image](https://user-images.githubusercontent.com/26086198/68801178-485ac700-063a-11ea-9877-7c16d8d0b630.png)

Maybe there's another reason for the tip?

**Comment by hairybreeches** [comment]
Hi Luis -

Yes, these are both excellent points.

We'll update the tip to mention that "long-running query" is more a matter of how many database writes take place during them, so can vary dramatically from table to table based on how frequently updated it is.

It's also possible that we get it wrong and there is no table bloat - this can happen when the rows are larger than we expect, and we'll explain that too.

Thanks for the advice

Dave

**Comment by hairybreeches** [comment]
I've updated the tip to include information about `AUTOVACUUM`, and frequently edited tables:

![2019-11-27_16-04-16](https://user-images.githubusercontent.com/709166/69739439-a2c25000-112f-11ea-8493-645d2e21aa71.png)

I didn't include anything about `VACUUM` taking a lock on the table, because according to the docs (https://www.postgresql.org/docs/current/routine-vacuuming.html), this only applies to `VACUUM FULL`:

"the standard form of VACUUM can run in parallel with production database operations. (Commands such as SELECT, INSERT, UPDATE, and DELETE will continue to function normally, though you will not be able to modify the definition of a table with commands such as ALTER TABLE while it is being vacuumed.) VACUUM FULL requires exclusive lock on the table it is working on, and therefore cannot be done in parallel with other use of the table. Generally, therefore, administrators should strive to use standard VACUUM and avoid VACUUM FULL."

Fixed in commit 53a7a6488261fcb790085971d210db1d30c24f06 deployed at 16:20 27/11/19
