### ISSUE TITLE
CTE optimisation

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#21]
Currently it is impossible to inline DML in PostgreSQL, so I think the hint is a bit misleading:
![image](https://user-images.githubusercontent.com/26086198/69052770-9b3fd000-09e6-11ea-8ddb-ef647ca7f1ad.png)

**Comment by hairybreeches** [comment]
Interesting point, thanks for raising it. I'll have a look at it, along with #20 in the next few weeks as part of a general audit of the tip conditions & text.

**Comment by hairybreeches** [comment]
I've updated the scoring so that we no longer recommend this when it's a DML query, since you're right that they can't be inlined, and I also believe the v12 improvements won't improve DML CTEs.

I've changed the first line of the text to read "This can lead to suboptimal plans for CTEs, particularly those returning results which are only referred to once in the rest of the query". This will still be shown even when the CTE is a DML query though, since we're keen for people to understand the issues & what they can do about them, even those which aren't a problem in the current query.

Fixed in commit fcbe6ed4b51e08a4f5cdb637e7329b5f7890d26b deployed at 12:05 3/12/19
