### ISSUE TITLE
Divide by zero error when no rows read from index-only scan

### ISSUE THREAD

**Issue by lrweck** [pgMustard/pgMustard#29]
75c89656-60f6-4aa1-ac77-251e558045e1

plan available at https://explain.depesz.com/s/VaZa

**Comment by mchristofides** [comment]
Thanks for reporting this, and sorry for the issue. I haven't been able to work out a fix or workaround in Dave's absence, but I'll bring it up with him when he's back from holiday.

My only viable theory so far is that this is the largest plan I've tried, at over 400kb, so it might be worth trying without VERBOSE just this once, in case that brings it below a threshold we're hitting somewhere.

In the meantime, I've added a bunch of credits to your account in case helpful.

**Comment by lrweck** [comment]
Another one: 6663b119-d7f4-4834-bb24-575ab46ce033

This is not even that big, just took a long time.

This is a good example of #22, too. This one does SELECTs, INSERTs, UPDATEs and DELETEs on the same "statement".

Thanks for your time.

**Comment by mchristofides** [comment]
Thanks Luís, the extra example will help us, and apologies again. It looks like my length theory was wrong. We'll get this/these fixed, thanks again.

**Comment by hairybreeches** [comment]
Hi Luis, 

Thanks for reporting this error. It turned out to be a divide by zero exception, when we were analysing an index-only scan which didn't read any rows/buffers.

It's fixed now, and I'd like to apologise again for how long it took us to sort this, we really hope this won't be how long we normally take to fix similar blocking issues. It was just unlucky that you hit it a couple of hours after I jumped on a Eurostar for two weeks of no-computer holiday in the countryside!

Fixed in commit e4a9cf6517f38154ffb99f8be36393a8681791b7 deployed at 9:30 18/12/19
