### ISSUE TITLE
Re-arrange temp I/O timings in details

### ISSUE THREAD

**Issue by rustprooflabs** [pgMustard/pgMustard#65]
Greetings!  Postgres 15 now includes `Temp I/O write time` and `Temp I/O read time`.  These details are included in the Operation detail section of a node.  Can they be moved to be next to the original `I/O write time` and `I/O read time` values?

An example of this [is this plan](https://app.pgmustard.com/#/explore/c206888d-24de-4a15-a213-0dfce76c348d?highlighted=0). The screenshot shows these new elements are at the end of the list, while the original items are nearly at the beginning. It'd be nice to see them all grouped together to be able to see the total I/O timings together.

![image](https://github.com/pgMustard/pgMustard/assets/3085224/aba35a7c-f49e-4001-9acf-b64ca7ee10c9)

**Comment by mchristofides** [comment]
@rustprooflabs great shout, thank you, done! We deliberately bumped the original I/O timings up the list, since they're more useful than most of the other fields we include in this section — so for now I've bumped these up to just below them.

I've also made a note to update our explain glossary with these fields, and will link to your blog post. Thanks again!
